SwinTransformerSys expand initial----depths:[2, 2, 2, 2];depths_decoder:[1, 2, 2, 2];drop_path_rate:0.1;num_classes:1
C:\Users\Shreeyut\AppData\Roaming\Python\Python313\site-packages\torch\functional.py:539: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:3638.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
---final upsample expand_first---
loading data from the directory: C:\Users\Shreeyut\deep-learning-lab\UNET-SWIN\SwinUNET_Flash_Attention\network\STARCOP\ang20190922t192642_r2048_c0_w512_h512-20250410T125838Z-001
Found 1 valid image-mask pairs
Traceback (most recent call last):
  File "C:\Users\Shreeyut\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
           ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Shreeyut\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_config.py", line 130, in __getitem__
    return self._items[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'batch_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Shreeyut\deep-learning-lab\UNET-SWIN\SwinUNET_Flash_Attention\network\trainer.py", line 47, in <module>
    batch_size=config.batch_size,
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Shreeyut\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_config.py", line 167, in __getattr__
    raise AttributeError(
        f"{self.__class__!r} object has no attribute {key!r}"
    ) from ke
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'batch_size'
